modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/ageing-mobs/issues"
license="MIT"

[[mods]]
modId="ageingmobs"
version="${file.jarVersion}"
displayName="Ageing Mobs Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ageing-mobs"
logoFile="logo.png"
authors="ShyNieke, Mrbysco"
credits="Plutosion for testing"
description='''
This mod allows mobs to age and transform.
'''
[[dependencies.ageingmobs]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="BOTH"